- name: Pull Prometheus docker exporter image from docker hub
  docker_image:
    source: pull
    name: "{{ prometheus_docker_exp_image }}"

- name: Create directory for config files Prometheus exporter
  file:
    path: /opt/prometheus-exp
    state: directory
    mode: '0755'

#- name: Copy config files for Prometheus exporter
#  copy:
#    src: "files/"
#    dest: "/opt/prometheus-exp/"
#    mode: 0777

- name: Copy template systemd Prometheus exporter
  template:
    src: prometheus-exp-temp.service.j2
    dest: "/etc/systemd/system/prometheus-exp-docker.service"
    owner: "root"
    group: "root"

- name: Start prometheus-exp-docker.service
  systemd:
    name: prometheus-exp-docker.service
    state: started
    enabled: yes
    daemon_reload: true

