---
- name: Pull Jenkins image from docker hub
  docker_image:
    source: pull
    name: "{{ jenkins_docker_image }}"

- name: Create directory for config files Jenkins
  file:
    path: /opt/jenkins
    state: directory
    mode: '0755'

- name: Copy config files for Jenkins
  copy:
    src: "files/"
    dest: "/opt/jenkins"
    mode: 0755

- name: Copy template systemd Jenkins
  template:
    src: jenkins-temp.service.j2
    dest: "/etc/systemd/system/jenkins-docker.service"
    owner: "root"
    group: "root"

- name: Start jenkins-docker.service
  systemd:
    name: jenkins-docker.service
    state: started
    enabled: yes
    daemon_reload: true
